### ISSUE TITLE
[Bug] Warm reset triggers inference hanging

### ISSUE THREAD

**Issue by vbrkicTT** [tenstorrent/tt-forge-fe#413]
# Description

Warm reset between pytests tests trigger occasionally hanging of inference on step ***Running model forward on device...***

Relates to #391. When running tests one by one with standalone warm reset (#391 Reproduce 2) hanging doesn't happen.

# Reproduce

    pytest -svv forge/test/operators/pytorch/test_inconsistency.py::test_binary_with_reset

**Comment by vbrkicTT** [comment]
The issue is still reproducible with the example from ticket description.

**Important note**
tt-smi currently used in sweep tests is quite old
`/home/software/syseng/wh/tt-smi -v`
> TT-SMI Version 2024-01-26-c1e6590dcb3a70f5 - Tenstorrent, Inc.

**Comment by vbrkicTT** [comment]
Tested today with latest build of tt-smi. The behavior has changed.  Though the original idea was to enable warm reset between tests is still not working. 

Today test:
- Before first test warm reset is executed successfully
- Between tests warm reset fails but tests continue by passing.

Log before first test

```log
Resetting board 0
Reset board 0 successful

Waiting for DRAM and ETH to train...
⠙ Detecting Tenstorrent Devices... (found 2)
```

Log between tests

```log
Traceback (most recent call last):
  File "tt_tools/common/api.py", line 566, in __init__
  File "tt_tools/common/api.py", line 602, in detect_pci
RuntimeError: BAR0 UC memory mapping failed for device 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tt_smi.py", line 579, in <module>
  File "tt_smi.py", line 356, in main
  File "tt_tools/common/api.py", line 594, in __init__
tenstorrent.tenstorrent.TTError: Failed to initialize TTHost.
[3044626] Failed to execute script 'tt_smi' due to unhandled exception!
```

**Comment by vbrkicTT** [comment]
Closed as stale. Reopen if needed.
